//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookBorrowReturnDetail
    {
        public int Id { get; set; }
        public int BookBorrowReturnId { get; set; }
        public int BookId { get; set; }
        public Nullable<byte> ReturnState { get; set; }
        public string Notes { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual BookBorrowReturn BookBorrowReturn { get; set; }
    }
}
