//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Id { get; set; }
        public int ReaderId { get; set; }
        public int BookTitleId { get; set; }
        public Nullable<byte> Point { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
    
        public virtual BookTitle BookTitle { get; set; }
        public virtual Reader Reader { get; set; }
    }
}
