//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemConfigParameter
    {
        public int Id { get; set; }
        public int Code { get; set; }
        public int Value { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string Description { get; set; }
        public Nullable<byte> Status { get; set; }
    }
}
