//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV.ResourceAccess.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ERP_Entities : DbContext
    {
        public ERP_Entities()
            : base("name=ERP_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN> ADMINS { get; set; }
    
        public virtual int ADMINS_ADD(string nEW_NAME)
        {
            var nEW_NAMEParameter = nEW_NAME != null ?
                new ObjectParameter("NEW_NAME", nEW_NAME) :
                new ObjectParameter("NEW_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADMINS_ADD", nEW_NAMEParameter);
        }
    
        public virtual int ADMINS_DELETE(Nullable<decimal> iD_DELETED)
        {
            var iD_DELETEDParameter = iD_DELETED.HasValue ?
                new ObjectParameter("ID_DELETED", iD_DELETED) :
                new ObjectParameter("ID_DELETED", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADMINS_DELETE", iD_DELETEDParameter);
        }
    
        public virtual int ADMINS_UPDATE(Nullable<decimal> iD_MODIFIED, string nAME_MODIFIED)
        {
            var iD_MODIFIEDParameter = iD_MODIFIED.HasValue ?
                new ObjectParameter("ID_MODIFIED", iD_MODIFIED) :
                new ObjectParameter("ID_MODIFIED", typeof(decimal));
    
            var nAME_MODIFIEDParameter = nAME_MODIFIED != null ?
                new ObjectParameter("NAME_MODIFIED", nAME_MODIFIED) :
                new ObjectParameter("NAME_MODIFIED", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADMINS_UPDATE", iD_MODIFIEDParameter, nAME_MODIFIEDParameter);
        }
    }
}
